Update ubuntu.yaml
Signed-off-by: Sudip Roy <123369437+sudip-ibm@users.noreply.github.com>

diff --git a/images/ubuntu.yaml b/images/ubuntu.yaml
--- a/images/ubuntu.yaml
+++ b/images/ubuntu.yaml
@@ -507,6 +507,14 @@ packages:
     - vm
 
   - packages:
+    - s390-tools
+    action: install
+    architectures:
+    - s390x
+    types:
+    - vm
+
+  - packages:
     - shim-signed
     action: install
     architectures:
@@ -569,6 +577,13 @@ actions:
   action: |-
     #!/bin/sh
     set -eux
+
+    # Force apt to use IPv4 to avoid failures on hosts with no IPv6 connectivity
+    mkdir -p /etc/apt/apt.conf.d
+    echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4
+
+    # Add hosts entry so apt does not need DNS to reach the ports mirror
+    echo "172.66.152.176 ports.ubuntu.com" >> /etc/hosts
 
     # Make sure systemd doesn't think it's running.
     [ ! -d /run/systemd ] && exit 0
@@ -685,6 +700,43 @@ actions:
     sed -i "s#root=[^ ]*#root=${DISTROBUILDER_ROOT_UUID}#g" /boot/grub/grub.cfg
   architectures:
   - ppc64el
+  types:
+  - vm
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    # Install zipl bootloader for s390x
+    LOOP_DEV="${DISTROBUILDER_LOOP_DEVICE}"
+    KERNEL=$(ls /boot/vmlinuz-* | head -n1)
+    INITRD=$(ls /boot/initrd.img-* | head -n1)
+
+    # Create zipl configuration
+    cat > /etc/zipl.conf <<'ZIPLEOF'
+    [defaultboot]
+    default = Ubuntu
+    target = /boot
+    targetbase = LOOPDEV_PLACEHOLDER
+    targettype = scsi
+    targetblocksize = 512
+    targetoffset = 2048
+
+    [Ubuntu]
+    image = KERNEL_PLACEHOLDER
+    ramdisk = INITRD_PLACEHOLDER
+    parameters = "root=ROOT_UUID_PLACEHOLDER ro console=ttysclp0"
+    ZIPLEOF
+    sed -i "s|KERNEL_PLACEHOLDER|${KERNEL}|" /etc/zipl.conf
+    sed -i "s|INITRD_PLACEHOLDER|${INITRD}|" /etc/zipl.conf
+    sed -i "s|ROOT_UUID_PLACEHOLDER|${DISTROBUILDER_ROOT_UUID}|" /etc/zipl.conf
+    sed -i "s|LOOPDEV_PLACEHOLDER|${LOOP_DEV}|" /etc/zipl.conf
+
+    # Install zipl
+    zipl -V -c /etc/zipl.conf
+  architectures:
+  - s390x
   types:
   - vm
 
